import {
  BookOpenText,
  Camera,
  CheckCircle2,
  Clapperboard,
  Hourglass,
  Images,
  Link2,
  MessageCircleHeart,
  Mic2,
  Settings2,
  Sparkles,
  UsersRound,
  XCircle,
} from "lucide-react";

export const appTitle = "A Story Called Elizabeth";
export const birthdayLabel = "August 19";

export const navLinks = [
  { href: "/", label: "Prelude" },
  { href: "/archive", label: "Archive" },
  { href: "/elizabeth/login", label: "Elizabeth" },
  { href: "/admin", label: "Admin" },
] as const;

export const archiveChapters = [
  {
    label: "Chapter 01",
    title: "Dear Elizabeth",
    kicker: "Opening letter",
    body: "A quiet beginning for the words that will welcome Elizabeth into her birthday archive.",
    quote: "Before the messages, before the photos, there is a letter that makes the whole room still.",
    accent: "gold",
    icon: BookOpenText,
  },
  {
    label: "Chapter 02",
    title: "The Girl We Know",
    kicker: "Portrait of her",
    body: "A chapter for the details people notice: her warmth, humor, faith, style, courage, and presence.",
    quote: "The story gathers the little things that make Elizabeth impossible to replace.",
    accent: "blush",
    icon: Sparkles,
  },
  {
    label: "Chapter 03",
    title: "Messages From Your People",
    kicker: "Birthday wishes",
    body: "A cinematic wall of private wishes from the people who love her and want their words kept here.",
    quote: "Every note becomes a frame in the birthday film.",
    accent: "lilac",
    icon: MessageCircleHeart,
  },
  {
    label: "Chapter 04",
    title: "Memories With You",
    kicker: "Shared moments",
    body: "A space for stories, inside jokes, soft recollections, and moments that still feel close.",
    quote: "Some memories are not loud. They simply stay.",
    accent: "espresso",
    icon: Clapperboard,
  },
  {
    label: "Chapter 05",
    title: "The Gallery",
    kicker: "Photo archive",
    body: "A polished gallery foundation for future portraits, candids, and collected photo cards.",
    quote: "The images will sit like keepsakes, handled with care.",
    accent: "gold",
    icon: Images,
  },
  {
    label: "Chapter 06",
    title: "Voices",
    kicker: "Audio and video",
    body: "A chapter reserved for the voice notes and short videos that will make the archive feel alive.",
    quote: "The sound of someone's voice can turn a page into a room.",
    accent: "lilac",
    icon: Mic2,
  },
  {
    label: "Chapter 07",
    title: "The Future We See For You",
    kicker: "Prayers and wishes",
    body: "A hopeful chapter for prayers, blessings, dreams, and the future people see opening for her.",
    quote: "This is where the archive looks forward.",
    accent: "blush",
    icon: Camera,
  },
  {
    label: "Final Chapter",
    title: "From Me",
    kicker: "Closing note",
    body: "A final private chapter, reserved for the personal message that closes the birthday story.",
    quote: "The last page should feel handwritten, intentional, and close.",
    accent: "espresso",
    icon: BookOpenText,
  },
] as const;

export const adminCards = [
  {
    title: "Total Submissions",
    description: "All birthday wishes received through private contributor links.",
    metricKey: "totalSubmissions",
    metric: "0 total",
    table: "birthday_submissions",
    schema: ["name", "relationship", "status", "created_at"],
    nextStep: "Build 4 will turn this count into a full review queue.",
    icon: MessageCircleHeart,
  },
  {
    title: "Pending Submissions",
    description: "Birthday wishes waiting for admin review before they can join the archive.",
    metricKey: "pendingSubmissions",
    metric: "0 pending",
    table: "birthday_submissions",
    schema: ["name", "relationship", "birthday_message", "status"],
    nextStep: "Review the moderation queue and decide what joins the archive.",
    icon: Hourglass,
  },
  {
    title: "Approved Submissions",
    description: "Birthday wishes approved for later archive rendering.",
    metricKey: "approvedSubmissions",
    metric: "0 approved",
    table: "birthday_submissions",
    schema: ["status", "admin_notes", "updated_at"],
    nextStep: "Build 5 will use approved rows for Elizabeth's archive.",
    icon: CheckCircle2,
  },
  {
    title: "Rejected Submissions",
    description: "Messages kept out of the final archive unless restored.",
    metricKey: "rejectedSubmissions",
    metric: "0 rejected",
    table: "birthday_submissions",
    schema: ["status", "admin_notes", "updated_at"],
    nextStep: "Rejected content remains available for admin records.",
    icon: XCircle,
  },
  {
    title: "Total Media Files",
    description: "Photos, voice notes, and videos uploaded with contributor submissions.",
    metricKey: "totalMediaFiles",
    metric: "0 files",
    table: "media_assets",
    schema: ["submission_id", "type", "storage_path", "status"],
    nextStep: "Open the media room to preview and moderate uploaded keepsakes.",
    icon: Images,
  },
  {
    title: "Pending Media Files",
    description: "Uploaded keepsakes waiting for admin review.",
    metricKey: "pendingMediaFiles",
    metric: "0 pending",
    table: "media_assets",
    schema: ["type", "status", "created_at"],
    nextStep: "Approve media independently from its linked written message.",
    icon: Camera,
  },
  {
    title: "Contributor Links",
    description: "All private invite tokens created for Elizabeth's people.",
    metricKey: "totalContributorLinks",
    metric: "0 links",
    table: "contributors",
    schema: ["token", "max_submissions", "expires_at"],
    nextStep: "Create, copy, and expire contributor links from the invite room.",
    icon: Link2,
  },
  {
    title: "Used Contributor Links",
    description: "Invite tokens that have reached their configured submission limit.",
    metricKey: "usedContributorLinks",
    metric: "0 used",
    table: "contributors",
    schema: ["token", "is_used", "max_submissions"],
    nextStep: "Used links can be reviewed beside their submission counts.",
    icon: UsersRound,
  },
  {
    title: "Archive Live",
    description: "Whether the final archive may be viewed when access rules allow it.",
    metricKey: "archiveLive",
    metric: "Locked",
    table: "archive_settings",
    schema: ["archive_live", "elizabeth_access_enabled"],
    nextStep: "Keep this off until the birthday reveal is ready.",
    icon: BookOpenText,
  },
  {
    title: "Contributions",
    description: "Whether private birthday submissions are currently open or closed.",
    metricKey: "contributionsOpen",
    metric: "Open",
    table: "archive_settings",
    schema: ["contributions_open", "birthday_date"],
    nextStep: "Admins can later control this from the settings screen.",
    icon: Settings2,
  },
] as const;
